import type { Product, Category, Order } from '@/lib/types';
import { placeholderImages } from './placeholder-images.json';

export const categories: { name: string; label: string }[] = [
  { name: 'clothing', label: 'Clothing' },
  { name: 'electronics', label: 'Electronics' },
  { name: 'accessories', label: 'Accessories' },
  { name: 'home-goods', label: 'Home Goods' },
  { name: 'books', label: 'Books' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Leather Jacket',
    slug: 'classic-leather-jacket',
    description: 'A timeless leather jacket for a stylish, edgy look.',
    longDescription: 'Crafted from 100% genuine leather, this jacket features a classic asymmetrical zip, multiple pockets, and a comfortable quilted lining. Perfect for any season, it adds a touch of rebellion to any outfit. Available in sizes S to XXL.',
    price: 299.99,
    category: 'clothing',
    images: placeholderImages.filter(img => img.id.includes('product-leather-jacket')),
    rating: 4.8,
    reviews: [
      { id: 'r1', author: 'Alex', rating: 5, comment: 'Amazing quality and fit!', date: '2023-10-20' },
      { id: 'r2', author: 'Jamie', rating: 4, comment: 'A bit stiff at first, but breaks in nicely.', date: '2023-10-15' },
    ],
  },
  {
    id: '2',
    name: 'Modern Smart Watch',
    slug: 'modern-smart-watch',
    description: 'Stay connected and track your fitness with this sleek smart watch.',
    longDescription: 'Features a vibrant AMOLED display, heart rate monitoring, GPS, and a 7-day battery life. Syncs with your smartphone for notifications and music control. Water-resistant up to 50 meters. Comes with a comfortable silicone strap.',
    price: 199.50,
    category: 'electronics',
    images: placeholderImages.filter(img => img.id.includes('product-smart-watch')),
    rating: 4.6,
    reviews: [
      { id: 'r3', author: 'Casey', rating: 5, comment: 'The best smart watch I\'ve owned. Battery is incredible.', date: '2023-11-05' },
    ],
  },
  {
    id: '3',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Immerse yourself in sound with these premium headphones.',
    longDescription: 'Experience industry-leading noise cancellation and superior sound quality. With up to 30 hours of battery life, touch controls, and a comfortable over-ear design, these headphones are perfect for travel, work, and everyday listening.',
    price: 349.00,
    category: 'electronics',
    images: placeholderImages.filter(img => img.id.includes('product-wireless-headphones')),
    rating: 4.9,
    reviews: [],
  },
  {
    id: '4',
    name: 'Urban Explorer Backpack',
    slug: 'urban-explorer-backpack',
    description: 'A versatile and durable backpack for city life and travel.',
    longDescription: 'Made from water-resistant canvas, this backpack has a padded laptop compartment (up to 15"), multiple organizational pockets, and comfortable, adjustable shoulder straps. Its minimalist design is perfect for the modern professional or student.',
    price: 89.99,
    category: 'accessories',
    images: placeholderImages.filter(img => img.id.includes('product-backpack')),
    rating: 4.7,
    reviews: [],
  },
  {
    id: '5',
    name: 'Pro-Comfort Running Shoes',
    slug: 'pro-comfort-running-shoes',
    description: 'Lightweight and responsive shoes for your daily run.',
    longDescription: 'Engineered with a breathable mesh upper and a high-rebound foam midsole, these shoes provide exceptional comfort and energy return. The durable rubber outsole offers excellent traction on various surfaces.',
    price: 120.00,
    category: 'clothing',
    images: placeholderImages.filter(img => img.id.includes('product-running-shoes')),
    rating: 4.5,
    reviews: [],
  },
  {
    id: '6',
    name: 'Artisan Drip Coffee Maker',
    slug: 'artisan-drip-coffee-maker',
    description: 'Brew the perfect cup of coffee every morning.',
    longDescription: 'This 8-cup coffee maker features advanced brewing technology for optimal flavor extraction. With a programmable timer, you can wake up to fresh coffee. The thermal carafe keeps your coffee hot for hours.',
    price: 75.50,
    category: 'home-goods',
    images: placeholderImages.filter(img => img.id.includes('product-coffee-maker')),
    rating: 4.4,
    reviews: [],
  },
  {
    id: '7',
    name: 'Minimalist LED Desk Lamp',
    slug: 'minimalist-led-desk-lamp',
    description: 'Brighten your workspace with this elegant desk lamp.',
    longDescription: 'An adjustable, flicker-free LED lamp with multiple brightness levels and color temperatures. Its sleek aluminum design and integrated USB charging port make it a stylish and functional addition to any desk.',
    price: 49.99,
    category: 'home-goods',
    images: placeholderImages.filter(img => img.id.includes('product-desk-lamp')),
    rating: 4.8,
    reviews: [],
  },
  {
    id: '8',
    name: 'The Silent Voyager (Hardcover)',
    slug: 'the-silent-voyager-hardcover',
    description: 'A gripping science fiction novel by J. F. Sterling.',
    longDescription: 'In the vastness of space, a lone astronaut must unravel a cosmic mystery to save humanity. A tale of isolation, discovery, and the human spirit. This award-winning novel is a must-read for sci-fi fans.',
    price: 24.95,
    category: 'books',
    images: placeholderImages.filter(img => img.id.includes('product-novel-book')),
    rating: 4.9,
    reviews: [],
  },
  {
    id: '9',
    name: 'Aviator Sunglasses',
    slug: 'aviator-sunglasses',
    description: 'Classic aviator sunglasses with polarized lenses.',
    longDescription: 'Protect your eyes in style with these timeless aviator sunglasses. Featuring a lightweight metal frame and 100% UV-protective polarized lenses, they reduce glare and provide crisp, clear vision.',
    price: 65.00,
    category: 'accessories',
    images: placeholderImages.filter(img => img.id.includes('product-sunglasses')),
    rating: 4.6,
    reviews: [],
  },
  {
    id: '10',
    name: 'Simple Ceramic Mug',
    slug: 'simple-ceramic-mug',
    description: 'A classic 12oz ceramic mug for your favorite beverage.',
    longDescription: 'Enjoy your morning coffee or tea in this simple yet elegant ceramic mug. Its sturdy handle and classic design make it a pleasure to use every day. Microwave and dishwasher safe.',
    price: 12.99,
    category: 'home-goods',
    images: placeholderImages.filter(img => img.id.includes('product-ceramic-mug')),
    rating: 4.7,
    reviews: [],
  }
];

export const orders: Order[] = [
    {
        id: 'ORD001',
        userId: 'user123',
        date: '2024-05-20',
        status: 'Delivered',
        total: 212.49,
        customer: {
          name: 'John Doe',
          email: 'john@example.com',
          address: '123 Main St',
          city: 'Anytown',
          state: 'CA',
          zip: '12345',
        },
        items: [
            { id: '2', name: 'Modern Smart Watch', price: 199.50, image: placeholderImages.find(img => img.id === 'product-smart-watch-1')!, quantity: 1, slug: 'modern-smart-watch' },
            { id: '10', name: 'Simple Ceramic Mug', price: 12.99, image: placeholderImages.find(img => img.id === 'product-ceramic-mug-1')!, quantity: 1, slug: 'simple-ceramic-mug' },
        ]
    },
    {
        id: 'ORD002',
        userId: 'user456',
        date: '2024-05-28',
        status: 'Processing',
        total: 120.00,
        customer: {
          name: 'Jane Smith',
          email: 'jane@example.com',
          address: '456 Oak Ave',
          city: 'Someville',
          state: 'NY',
          zip: '67890',
        },
        items: [
             { id: '5', name: 'Pro-Comfort Running Shoes', price: 120.00, image: placeholderImages.find(img => img.id === 'product-running-shoes-1')!, quantity: 1, slug: 'pro-comfort-running-shoes' },
        ]
    }
]
